---
title: "Econometrics Final Project"
author: "David Almonte"
date: "4/22/2019"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(fastDummies) #this lets us automaticaly turn
library(tidyverse)
library(reshape2)
library(corrplot)
library(stargazer)
library(dplyr)
library(car)
variables_classes = sapply
```

```{r 005_Import Data}
test <- read.csv("test.csv") # test data has no sale price
homes <- read.csv("train.csv") # training data contains sale price
sample_submission <- read.csv("sample_submission.csv")
```

```{r 010_Variable Selection}
# Choosing Variables
lm_vars <- c("SalePrice", # Dvar
             "MoSold", # An integer. We will turn it into 12, then
             "YrSold",
             "GrLivArea", # Abv ground living area
             "GarageArea",
             "Condition1", # Proximity to railroad
             "Condition2",
             "BsmtQual", # basementheight
             "LotArea",
             "Fireplaces",
             "HeatingQC",
             "FullBath")

homes_a <- homes%>%
  subset(SaleCondition != "Family",
         SaleCondition != "Abnormal")
```

```{r}
homes_a[,"MoSold"] <-factor(homes_a[,"MoSold"])
homes_a[,"YrSold"] <-factor(homes_a[,"YrSold"])
homes_b <- homes_a[lm_vars]
```

```{r 100 Creating Dummy Variables}
homes_c <- homes_b%>%
  dummy_cols(sort_columns = TRUE)
homes_d <- homes_c[sapply(homes_c, is.numeric)]
homes_e <- homes_d%>%
  mutate(lnSalePrice = log(SalePrice),
         lnGrLivArea = log(GrLivArea),
         lnLotArea = log(LotArea))
```

```{r}
#Creating Quarterly Dummies
homes_f <- homes_e%>%
  mutate(QSold_1 = MoSold_12 + MoSold_1 + MoSold_2,
         QSold_2 = MoSold_3 + MoSold_4 + MoSold_5,
         QSold_3 = MoSold_6 + MoSold_7 + MoSold_8,
         QSold_4 = MoSold_9 + MoSold_10 + MoSold_11)

homes_g <- homes_f[, !names(homes_f) %in% c("MoSold_1",
                                            "MoSold_2",
                                            "MoSold_3",
                                            "MoSold_4",
                                            "MoSold_5",
                                            "MoSold_6",
                                            "MoSold_7",
                                            "MoSold_8",
                                            "MoSold_9",
                                            "MoSold_10",
                                            "MoSold_11",
                                            "MoSold_12"
                                            )]
```

```{r Regressions, results = 'asis'}
# We specify a model of home prices answering question 1:
# Ground Floor Square Footage
yhat1 <- lm(lnSalePrice ~ lnGrLivArea, data = homes_g)
stargazer(yhat1, title="Figure 1", align = TRUE, type='html')


yhat2 <- lm(lnSalePrice ~ lnGrLivArea + lnLotArea, data = homes_g)
stargazer(yhat2, title="Figure 2", align = TRUE, type='html')


yhat3 <- lm(lnSalePrice ~ lnGrLivArea + lnLotArea + GarageArea, data = homes_g)
stargazer(yhat3, title="Figure 3", align = TRUE, type='html')


yhat4 <- lm(lnSalePrice ~ lnGrLivArea + lnLotArea + GarageArea + QSold_2 + QSold_3 + QSold_4, data = homes_g)
stargazer(yhat4, title="Figure 4", align = TRUE, type='html')
linearHypothesis(yhat4, "QSold_2 + QSold_3 + QSold_4 = 0")


yhat5 <- lm(lnSalePrice ~ lnGrLivArea + lnLotArea + GarageArea + Condition1_Norm, data = homes_g)
stargazer(yhat5, title="Figure 5", align = TRUE, type='html')


yhat6 <- lm(lnSalePrice ~ lnGrLivArea + lnLotArea + GarageArea + Condition1_Norm + BsmtQual_Ex + BsmtQual_Gd + BsmtQual_Fa , data = homes_g)
stargazer(yhat6, title="Figure 6", align = TRUE, type='html')


yhat7 <- lm(lnSalePrice ~ lnGrLivArea + lnLotArea + GarageArea + Condition1_Norm + BsmtQual_Ex + BsmtQual_Gd + BsmtQual_Fa + Fireplaces, data = homes_g)
stargazer(yhat7, title="Figure 7", align = TRUE, type='html')


yhat8 <- lm(lnSalePrice ~ lnGrLivArea + lnLotArea + GarageArea + Condition1_Norm + BsmtQual_Ex + BsmtQual_Gd + BsmtQual_Fa + Fireplaces + HeatingQC_Ex + HeatingQC_Gd + HeatingQC_Fa, data = homes_g)
stargazer(yhat8, title="Figure 8", align = TRUE, type='html')
```










