---
title: "MRDC Educational Practices Quantitative Analysis"
author: "David Almonte"
date: "3/18/2019"
output: html_document
---

#### Import Libraries 
```{r setup, include=FALSE}
library(dplyr)
library(writexl)
library(ggplot2)
library(tidyverse)
library(prettyR)
```

#### Import Datasets
```{r Loading }
Students <- read.csv("37046-0001-Data.csv")
Teachers <- read.csv("37046-0004-Data.csv")
```

#### Wrangling
```{r Student Data Wrangling}
# Slect Relvant Variables Student dataframe
StudentVars <- c("XSCHID", 
                 "SPED",
                 "TSTSS",
                 "TSTSS_BL",
                 "TSTSSTAND",
                 "TSTSSTAND_BL",
                 "MALE",
                 "BLACK",
                 "HISPANIC",
                 "WHITE",
                 "ASIAN",
                 "AGE",
                 "ELL",
                 "FRLUNCH",
                 "GRADE",
                 "COHORT1")

ObsDNAVars <- c( "SPED",
                 "MALE",
                 "BLACK",
                 "HISPANIC",
                 "WHITE",
                 "ASIAN",
                 "ELL",
                 "FRLUNCH",
                 "COHORT1")

# Drop Students with missing relevant data from dataframe, constructs new variables. # Mutates to convert strings to numeric.
Students_Subset_01 <- Students[StudentVars]%>%
  drop_na()%>%
  mutate(TSTSSTAND_DELTA = TSTSSTAND - TSTSSTAND_BL,
        ScoreScale = ifelse(TSTSS > 500, 1, 0),
        TSTSS_DELTA = TSTSS - TSTSS_BL,
        SPED = ifelse(SPED == "(1) observation is applicable", 1, 0),
        MALE = ifelse(MALE == "(1) observation is applicable", 1, 0),
        BLACK = ifelse(BLACK == "(1) observation is applicable", 1, 0),
        HISPANIC = ifelse(HISPANIC == "(1) observation is applicable", 1, 0),
        WHITE = ifelse(WHITE == "(1) observation is applicable", 1, 0),
        ASIAN = ifelse(ASIAN == "(1) observation is applicable", 1, 0),
        ELL = ifelse(ELL == "(1) observation is applicable", 1, 0),
        FRLUNCH = ifelse(FRLUNCH == "(1) observation is applicable", 1, 0),
        COHORT1 = ifelse(COHORT1 == "(1) observation is applicable", 1, 0))
```

```{r Teacher Data Wrangling}
# Selects Relvant Variables from Teacher Dataframe
TeacherVars <- c("XSCHID", 
                 "TREAT", 
                 "TSQ39_15", 
                 "TSQ40A_15", 
                 "TSQ40B_15", 
                 "TSQ40C_15", 
                 "TSQ40D_15", 
                 "TSQ40E_15")

# Recoding variables from teachers to those suitable for computation
Teacher_Subset_01 <- Teachers[TeacherVars]%>%
  drop_na()%>%
  mutate(TREAT     = ifelse(TREAT     == "(1) Treatment", 1, 0),
         TSQ39_15  = ifelse(TSQ39_15  == "(1) You feel extremely prepared", 1, 0),
         TSQ40A_15 = ifelse(TSQ40A_15 == "(1) Selected", 1, 0),
         TSQ40B_15 = ifelse(TSQ40B_15 == "(1) Selected", 1, 0),
         TSQ40C_15 = ifelse(TSQ40C_15 == "(1) Selected", 1, 0),
         TSQ40D_15 = ifelse(TSQ40D_15 == "(1) Selected", 1, 0),
         TSQ40E_15 = ifelse(TSQ40E_15 == "(1) Selected", 1, 0))
```



```{r School-wide summary Stats}
# Computes the average schoolwide scores.
Avg_School_Scores <- Students_Subset_01 %>%
  group_by(XSCHID)%>%
  summarize(mean_improvement = mean(TSTSSTAND_DELTA, na.rm = TRUE))

Avg_School_Preparedness <- Teacher_Subset_01%>%
  group_by(XSCHID)%>%
  summarize(TSQ39_15 = mean(TSQ39_15),
            TSQ40A_15 = mean(TSQ40A_15),
            TSQ40B_15 = mean(TSQ40B_15),
            TSQ40C_15 = mean(TSQ40C_15),
            TSQ40D_15 = mean(TSQ40D_15),
            TSQ40E_15 = mean(TSQ40E_15))%>%
  mutate(prep_score = 
           TSQ39_15 + TSQ40A_15 + TSQ40B_15 + 
           TSQ40C_15 + TSQ40D_15 + TSQ40E_15)
            
# Merges Dataframes across schools
School_Stats <- merge(Avg_School_Scores, Avg_School_Preparedness, by = "XSCHID", incomparables = NULL)
Students_Subset_01 <- merge(Students_Subset_01, School_Stats, by.X=XSCHID)
```


```{r Linear Models}
# Conducts a linear regression to test the relationship betweeen school level average test scores and average preeparedneses. 
yhat <- lm(mean_improvement ~ prep_score, data = School_Stats)

yhat2 <- lm(mean_improvement ~ TSQ39_15 + TSQ40A_15 + TSQ40B_15 + TSQ40C_15 + TSQ40D_15 + TSQ40E_15, data = School_Stats)

yhat3 <- lm((TSTSSTAND_DELTA) ~ prep_score , data = Students_Subset_01)
summary(yhat3)

yhat4 <- lm((TSTSSTAND_DELTA) ~ TSQ39_15 + TSQ40A_15 + TSQ40B_15 + TSQ40C_15 + TSQ40D_15 + TSQ40E_15, data = Students_Subset_01)
confint(yhat4)
```


```{r Graphing}
# Generates a smaller dataset of randomly selected students, then generates scattreplots. 
Students_Subset_02 <- sample_n(Students_Subset_01, 1500)
ggplot(Students_Subset_02, aes(x=TSQ40B_15, y=(TSTSSTAND_DELTA))) +
  geom_point(size=0.1, shape= 23,  position =  position_jitter(w = 0.05, h = 0.), alpha =0.3)+
  geom_smooth(method='lm')+
  xlim(0, 1)+
  ylim(-2, 2)

ggplot(Students_Subset_02, aes(x=TSQ40A_15, y=(TSTSSTAND_DELTA))) +
  geom_point(size=0.1, shape= 23,  position =  position_jitter(w = 0.05, h = 0.17), alpha =0.3)+
  geom_smooth(method='lm')+
  xlim(0, 1)+
  ylim(-2, 2)
```

